# config.py

from pathlib import Path

# Base project directories
BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"

# --- Directory Settings ---
# The main directory where all user-uploaded and indexed files are stored.
CACHE_DIR = DATA_DIR / "IDXDB"

# A dedicated directory for storing files generated by the "Mixup" feature.
# This helps keep the main directory clean.
GENERATED_FILES_DIR = DATA_DIR / "generated"


# --- File Settings ---
# The name of the CSV file that stores the search index created by FiberDBMS.
# This file is crucial for the chatbot and search functionalities.
INDEX_FILE = DATA_DIR / "arcana_index.csv"

# App settings stored outside source control.
APP_SETTINGS_FILE = DATA_DIR / "app_settings.json"
DEFAULT_PASSWORD_LOGIN = False


# --- Application Settings ---
# The title of the Streamlit application.
APP_TITLE = "Arcana"

# A list of supported file extensions that the application can process and index.
SUPPORTED_FILE_TYPES = ["txt", "pdf", "csv", "docx", "pptx"]

# For long response (Qwen model)
QWEN_API_KEY = ""  # Enter your Qwen API key here
QWEN_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
